### ISSUE TITLE
Substructure vs. Constant Records 

### ISSUE THREAD

**Issue by PrometheusPi** [openPMD/openPMD-validator#10]
This **question** arises from [a pull request](https://github.com/ComputationalRadiationPhysics/picongpu/pull/1053) in [PIConGPU](https://github.com/ComputationalRadiationPhysics/picongpu):

Is it possible to add a substructure to openPMD compatible files that s **not interpreted** as [**constant record**](https://github.com/openPMD/openPMD-standard/blob/latest/STANDARD.md#constant-record-components)?

```
.../record - Group
.../record/A - Group
.../record/A/data1 - Dataset
.../record/A/data2 - Dataset
.../record/B - Group
.../record/B/data1 - Dataset
.../record/B/data2 - Dataset
```

**Comment by ax3l** [comment]
the problem is that you created a sub-group `A` inside a mesh record named `record`. that is not allowed and will be interpreted as a `constant component` with name `A` which needs `value` and `shape`.

> Is it possible to add a substructure to openPMD compatible files that s not interpreted as constant record?

no. if your data set would be 1D you could use particles for that.

**Comment by PrometheusPi** [comment]
Thanks @ax3l for the fast reply.
