### ISSUE TITLE
PyPI: Package

### ISSUE THREAD

**Issue by ax3l** [openPMD/openPMD-validator#16]
For convenience we could package those scripts. Versioning should be the same as the standard it tests + a 4th `tweak` level for script updates.

**Comment by ax3l** [comment]
ccing @t184256 :)

**Comment by t184256** [comment]
Quick question: are you fine with a dependency on [pbr](https://docs.openstack.org/pbr/latest/) or would you prefer the vanilla way?

**Comment by ax3l** [comment]
I didn't even know `pbr` before, interesting! :)

**Comment by t184256** [comment]
It's a nice thing, actually. You can compare the pull requests.

I couldn't think of a way of convincing `pbr` I don't want packages, so I gave in and created one. The `py_packages` I went with in another pull request is seemingly a deprecated `distutils`-era trickery.
