### ISSUE TITLE
Wrong link

### ISSUE THREAD

**Issue by Flamefire** [openPMD/openPMD-validator#17]
The implementations link is wrong.
Current: https://github.com/openPMD/openPMD/blob/1.0.0/STANDARD.md#implementations
Correct: https://github.com/openPMD/openPMD-standard/blob/latest/STANDARD.md#implementations

**Comment by ax3l** [comment]
argh ;) should actually be https://github.com/openPMD/openPMD-standard/blob/1.0.0/STANDARD.md#implementations

**Comment by Flamefire** [comment]
You swapped the names in your comment. Doc update was correct though ;)

**Comment by ax3l** [comment]
yes, updated the comment after initial posting because I pasted _again_ a wrong link ;)
