### ISSUE TITLE
Exception on missing meshes path & Return code

### ISSUE THREAD

**Issue by Flamefire** [openPMD/openPMD-validator#18]
With PIC extension there will be a `KeyError` thrown when the meshes don't exist:

> Found 1 iteration(s)
> Iteration 0 : found 0 meshes
>     result_array += check_iterations(f, verbose, extension_pic)
>   File "/home/grund59/Dokumente/XRayTracing/src/testBuilds/build_ModuleTest_cmake6/installed/buildSystem/checkOpenPMD_h5.py", line 452, in check_iterations
>     result_array += check_meshes(f, iteration, v, pic)
>   File "/home/grund59/Dokumente/XRayTracing/src/testBuilds/build_ModuleTest_cmake6/installed/buildSystem/checkOpenPMD_h5.py", line 599, in check_meshes
>     result_array += test_attr(f[full_meshes_path], v, "required",
>   File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip_build_root/h5py/h5py/_objects.c:2574)
>   File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip_build_root/h5py/h5py/_objects.c:2533)
>   File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/group.py", line 164, in __getitem__
>     oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
>   File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip_build_root/h5py/h5py/_objects.c:2574)
>   File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip_build_root/h5py/h5py/_objects.c:2533)
>   File "h5py/h5o.pyx", line 190, in h5py.h5o.open (/tmp/pip_build_root/h5py/h5py/h5o.c:3546)
> KeyError: "Unable to open object (Object 'meshes' doesn't exist)"

Additionally the return code does not seem to be set to an error state (at least) in this case.

Edit: Return codes seem never to be set. Please return an error code when any error or exception occurred so this can be used in tools.

**Comment by ax3l** [comment]
both closed, thanks for the notice!
