### ISSUE TITLE
Windows: no numpy float128

### ISSUE THREAD

**Issue by ax3l** [openPMD/openPMD-validator#63]
On Windows:
```
module 'numpy' has no attribute `float128`. Did you mean `float16`?
```
Probably Windows numpy calls `long double`s differently.

First seen by @ldoyle :+1:

**Comment by ax3l** [comment]
Classic problem: https://github.com/quantumlib/Cirq/issues/1511#issuecomment-481427402

We should use use the named types over the fixed byte ones:
https://en.cppreference.com/w/cpp/language/types

On Windows, `long double` is not 128 bit but usually something like 80 bit.

**Comment by ax3l** [comment]
Fix via #65

**Comment by ldoyle** [comment]
Thanks for the quick fix! I also quickly checked online and an alternative approach might be to use `isinstance(value, np.floating)` for a generic approach. See examples in:

https://stackoverflow.com/questions/28292542/how-to-check-if-a-number-is-a-np-float64-or-np-float32-or-np-float16

However this would require a refactor of `test_attr` and seems more complicated than your fix.

**Comment by ax3l** [comment]
Thanks!

That's good to know in case we start to support more exotic floating point numbers that are not part of the fundamental C language types.
